name: geo_elevation_lookup
description: A Dart and Flutter package that provides the ability to retrieve elevation data from geographical coordinates (latitude and longitude).
version: 0.0.1
homepage: https://github.com/sikandernoori/geo_elevation_lookup

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
